application: your-app-id
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static 

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.py
  secure: optional
